name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install Dependencies & Trick Buildozer
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y \
          build-essential libffi-dev libssl-dev python3-dev \
          libltdl-dev autoconf automake libtool pkg-config cmake \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
          unzip zip ant

          # --- THE TRICK ---
          # 1. Create the folder where Buildozer looks for Ant
          mkdir -p ~/.buildozer/android/platform/apache-ant-1.9.4
          
          # 2. Copy the system Ant into that folder
          # This makes Buildozer think it successfully downloaded Ant 1.9.4
          cp -r /usr/share/ant/* ~/.buildozer/android/platform/apache-ant-1.9.4/

      # 4. Clean Cache (Only bin, keep the fake ant we just made)
      - name: Clean Cache
        run: |
          rm -rf bin

      # 5. Build the APK
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 6. Upload the result
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
